# Generated by Django 5.1.6 on 2025-02-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contact_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="message",
            new_name="desc",
        ),
    ]
